name: Repository File
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Artifact Encrypted"]
    types:
      - completed

jobs:
  repository_file:
    runs-on: ubuntu-latest
    name: Repository File
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh_access_token }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: |
          terraform plan -var="run_id=${{ github.run_id }}"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var="run_id=${{ github.run_id }}"

      - name: List all files and directories
        run: |
          echo "List all directories and files in the GitHub workspace"
          ls -R

      - name: Commit Repository File
        uses: badgerhobbs/terraform-state@v2
        with:
          operation: upload
          location: repository
