name: Repository File Encrypted
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Repository File"]
    types:
      - completed

jobs:
  repository_file_encrypted:
    runs-on: ubuntu-latest
    name: Repository File Encrypted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.gh_access_token }}

      - name: Decrypt Repository File
        uses: badgerhobbs/terraform-state@v1
        with:
          encryption_key: ${{ secrets.encryption_key }}
          operation: download
          location: repository
        continue-on-error: true

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Run Terraform Plan
        run: |
          terraform plan -var="run_id=${{ github.run_id }}"

      - name: Run Terraform Apply
        run: |
          terraform apply -auto-approve -var="run_id=${{ github.run_id }}"

      - name: List all files and directories
        run: |
          echo "List all directories and files in the GitHub workspace"
          ls -R

      - name: Encrypt and Commit Repository File
        uses: badgerhobbs/terraform-state@v1
        with:
          encryption_key: ${{ secrets.encryption_key }}
          operation: upload
          location: repository
